#ifndef GDSP_SELECTION
#define GDSP_SELECTION

#define GDSP_ADPCMNBDECODER
#define GDSP_ADPCMNBENCODER
#define GDSP_CLASSDDESTINATIONS
#define GDSP_CODECDESTINATIONS
#define GDSP_CODECSOURCE
#define GDSP_PCMMASTERDESTINATIONS
#define GDSP_PCMSOURCE
#define GDSP_CONSTANT
#define GDSP_DTMFDETECTOR
#define GDSP_GAIN
#define GDSP_LAWLIN
#define GDSP_PAEC
#define GDSP_PLAYBACKBUFFER
#define GDSP_PLAYBACKBUFFER
#define GDSP_PLEVDET
#define GDSP_RECORDBUFFER
#define GDSP_SINGLETONEDETECTOR
#define GDSP_SUMMATOR
#define GDSP_TONEGEN
#define GDSP_AGC
#define GDSP_DURATIONCOUNTER

#endif
