#ifndef GDSP_MDL2CODE_SIZE_DEFINES_H
#define GDSP_MDL2CODE_SIZE_DEFINES_H

// Defines to help setup DSP memory

#define GDSP_MAX_MDL2CODE_FUNCTIONS_DSP1_BACKGND (1)
#define GDSP_MAX_MDL2CODE_CODESIZE_DSP1_BACKGND (2)
#define GDSP_MAX_MDL2CODE_DATASIZE_DSP1_BACKGND (997)


#define GDSP_MAX_MDL2CODE_FUNCTIONS_DSP1_8KHZ (16)
#define GDSP_MAX_MDL2CODE_CODESIZE_DSP1_8KHZ (44)
#define GDSP_MAX_MDL2CODE_DATASIZE_DSP1_8KHZ (491)


#define GDSP_MAX_MDL2CODE_FUNCTIONS_DSP1_16KHZ (0)
#define GDSP_MAX_MDL2CODE_CODESIZE_DSP1_16KHZ (0)
#define GDSP_MAX_MDL2CODE_DATASIZE_DSP1_16KHZ (0)


#define GDSP_MAX_MDL2CODE_FUNCTIONS_DSP2_BACKGND (0)
#define GDSP_MAX_MDL2CODE_CODESIZE_DSP2_BACKGND (0)
#define GDSP_MAX_MDL2CODE_DATASIZE_DSP2_BACKGND (0)


#define GDSP_MAX_MDL2CODE_FUNCTIONS_DSP2_8KHZ (0)
#define GDSP_MAX_MDL2CODE_CODESIZE_DSP2_8KHZ (0)
#define GDSP_MAX_MDL2CODE_DATASIZE_DSP2_8KHZ (0)


#define GDSP_MAX_MDL2CODE_FUNCTIONS_DSP2_16KHZ (0)
#define GDSP_MAX_MDL2CODE_CODESIZE_DSP2_16KHZ (0)
#define GDSP_MAX_MDL2CODE_DATASIZE_DSP2_16KHZ (0)

#endif // GDSP_MDL2CODE_SIZE_DEFINES_H 
